#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED

#include <stdint.h>

const uint32_t VIEWPORT_WIDTH = 640;
const uint32_t VIEWPORT_HEIGHT = 480;
const uint32_t VIEWPORT_PIXELS = VIEWPORT_WIDTH * VIEWPORT_HEIGHT;

#endif // GLOBAL_H_INCLUDED
