#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED

#include <stdint.h>

const float DEG2RAD = 3.14159265f/180.0f;

const uint32_t VIEWPORT_WIDTH = 1024;
const uint32_t VIEWPORT_HEIGHT = 768;
const uint32_t VIEWPORT_PIXELS = VIEWPORT_WIDTH * VIEWPORT_HEIGHT;

#endif // GLOBAL_H_INCLUDED
